# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loans-deployment
serviceName: loans
appLabel: loans
appName: loans
dbURL: jdbc:postgresql://postgresql.default.svc.cluster.local:5432/postgres?currentSchema=card&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
replicaCount: 1

image:
  repository: manite/loans-img
  tag: s5

containerPort: 8085

service:
  type: LoadBalancer
  port: 8085
  targetPort: 8085

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
rabbit_enabled: true
db_enabled: true