eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

genral:
 phone: 0507156888


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
