spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://gitlab.com/mazen.abono7tah/spring-app-config.git
          default-label: main
          timeout: 5
          force-pull: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  # active: native
  #cloud:
  #  config:
  #    server:
  #      native:
  #        search-locations: "classpath:/config"
  #config:
  #  import: optional:configserver:https://gitlab.com/mazen.abono7tah/spring-app-config
server:
  port: 8090
logging:
  level:
    com:
      bank:
        tech:
          configserver: debug
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
#encrypt:
#  key: "DFO5648H9G33GH5Vb3W9PQ6"